version: "3.7"
services:
  lakshmiService:
    build:
      context: .
      dockerfile: Dockerfile
    image: lakshmi-service
    container_name: LakshmiService
    hostname: has.prod.lakshmi-service
    restart: on-failure
networks:
  default:
    name: "nginx_default"
    external: true
